"use client";

import React, { useRef } from "react";
import {
  X, Stethoscope, Pill, Clock, UtensilsCrossed, CalendarDays,
  FileText, Download, AlertCircle
} from "lucide-react";
import { Prescription, MedicationItem } from "@/services/appointmentsService";

interface PrescriptionViewProps {
  prescription: Prescription;
  doctorName?: string | null;
  onClose: () => void;
}

function formatTiming(timing: string[]): string {
  return timing
    .map((t) => t.charAt(0).toUpperCase() + t.slice(1))
    .join(", ");
}

function formatFood(food: MedicationItem["food"]): string {
  return food === "after" ? "After food" : "Before food";
}

export default function PrescriptionView({ prescription, doctorName, onClose }: PrescriptionViewProps) {
  const printRef = useRef<HTMLDivElement>(null);

  const consultDate = new Date(prescription.created_at).toLocaleDateString("en-IN", {
    timeZone: "Asia/Kolkata",
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const handlePrint = () => {
    const content = printRef.current?.innerHTML;
    if (!content) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html>
        <head>
          <title>Prescription — UniCare</title>
          <style>
            body { font-family: system-ui, sans-serif; padding: 2rem; color: #1a1c1f; }
            h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
            .meta { color: #717786; font-size: 0.9rem; margin-bottom: 1.5rem; }
            table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
            th { text-align: left; padding: 0.5rem 0.75rem; background: #f3f3f8; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; }
            td { padding: 0.65rem 0.75rem; border-bottom: 1px solid #e2e2e7; font-size: 0.9rem; }
            .section { margin-bottom: 1.5rem; }
            .section-title { font-weight: 700; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.1em; color: #717786; margin-bottom: 0.5rem; }
            .footer { margin-top: 2rem; font-size: 0.75rem; color: #717786; }
          </style>
        </head>
        <body>
          <h1>Prescription</h1>
          <p class="meta">Dr. ${doctorName || "Doctor"} · ${consultDate} · UniCare</p>
          ${content}
          <p class="footer">Generated by UniCare Health Wallet · ${new Date().toLocaleString("en-IN")}</p>
        </body>
      </html>
    `);
    win.document.close();
    win.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 bg-black/70 backdrop-blur-sm animate-in fade-in duration-300">
      <div className="bg-surface-container-lowest w-full sm:max-w-xl rounded-t-[2.5rem] sm:rounded-[3rem] shadow-ambient overflow-hidden flex flex-col max-h-[95vh] animate-in slide-in-from-bottom-4 sm:zoom-in-95 duration-300">
        {/* Header */}
        <header className="p-7 pb-4 flex justify-between items-center bg-surface-container-low shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-2xl bg-gradient-to-br from-secondary/70 to-secondary text-on-secondary flex items-center justify-center shadow-lg shadow-secondary/20">
              <Pill className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-headline-md font-manrope font-bold text-on-surface">Prescription</h2>
              <p className="text-label-sm font-bold text-on-surface-variant/70">
                {doctorName ? `Dr. ${doctorName}` : "Doctor"} · {consultDate}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              title="Download / Print"
              className="w-10 h-10 flex items-center justify-center rounded-full bg-surface-container-high hover:bg-surface-container-highest text-on-surface-variant hover:text-on-surface transition-all"
            >
              <Download className="w-4 h-4" />
            </button>
            <button
              onClick={onClose}
              className="w-10 h-10 flex items-center justify-center rounded-full hover:bg-surface-container-high text-on-surface-variant transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </header>

        <div className="p-7 overflow-y-auto no-scrollbar space-y-6">
          {/* Printable content */}
          <div ref={printRef} className="space-y-6">
            {/* Doctor info row */}
            <div className="flex items-center gap-3 p-4 bg-surface-container-low rounded-[1.5rem]">
              <Stethoscope className="w-5 h-5 text-tertiary shrink-0" />
              <div>
                <p className="text-body-md font-bold text-on-surface">{doctorName ? `Dr. ${doctorName}` : "Doctor"}</p>
                <p className="text-label-sm text-on-surface-variant font-medium">{consultDate}</p>
              </div>
            </div>

            {/* Diagnosis */}
            {prescription.diagnosis && (
              <div className="section">
                <p className="flex items-center gap-1.5 text-label-md font-bold uppercase tracking-widest text-on-surface-variant mb-3">
                  <FileText className="w-3 h-3" /> Diagnosis
                </p>
                <div className="p-5 bg-primary/5 border border-primary/15 rounded-[1.5rem]">
                  <p className="text-body-md text-on-surface font-medium leading-relaxed">{prescription.diagnosis}</p>
                </div>
              </div>
            )}

            {/* Medications */}
            {prescription.medications && prescription.medications.length > 0 ? (
              <div className="section">
                <p className="flex items-center gap-1.5 text-label-md font-bold uppercase tracking-widest text-on-surface-variant mb-3">
                  <Pill className="w-3 h-3" /> Medications
                </p>
                <div className="rounded-[1.5rem] overflow-hidden border border-outline-variant/30">
                  {/* Table header */}
                  <div className="grid grid-cols-12 bg-surface-container-low px-4 py-3 gap-2">
                    <p className="col-span-5 text-label-sm font-bold uppercase tracking-wider text-on-surface-variant">Medicine</p>
                    <p className="col-span-3 text-label-sm font-bold uppercase tracking-wider text-on-surface-variant">Timing</p>
                    <p className="col-span-2 text-label-sm font-bold uppercase tracking-wider text-on-surface-variant">Food</p>
                    <p className="col-span-2 text-label-sm font-bold uppercase tracking-wider text-on-surface-variant">Days</p>
                  </div>
                  {/* Rows */}
                  {prescription.medications.map((med, idx) => (
                    <div
                      key={idx}
                      className={`grid grid-cols-12 px-4 py-4 gap-2 items-center ${
                        idx % 2 === 0 ? "bg-surface-container-lowest" : "bg-surface-container-low/50"
                      }`}
                    >
                      <div className="col-span-5 flex items-center gap-2">
                        <div className="w-6 h-6 rounded-full bg-secondary/10 text-secondary flex items-center justify-center shrink-0">
                          <Pill className="w-3 h-3" />
                        </div>
                        <p className="text-label-md font-bold text-on-surface leading-tight">{med.name}</p>
                      </div>
                      <div className="col-span-3 flex items-center gap-1">
                        <Clock className="w-3 h-3 text-on-surface-variant shrink-0" />
                        <p className="text-label-sm font-medium text-on-surface-variant">{formatTiming(med.timing)}</p>
                      </div>
                      <div className="col-span-2 flex items-center gap-1">
                        <UtensilsCrossed className="w-3 h-3 text-on-surface-variant shrink-0" />
                        <p className="text-label-sm font-medium text-on-surface-variant">{formatFood(med.food)}</p>
                      </div>
                      <div className="col-span-2">
                        <span className="px-2.5 py-1 bg-tertiary/10 text-tertiary rounded-full text-label-sm font-bold">
                          {med.days}d
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <div className="flex items-center gap-3 p-4 bg-surface-container-low rounded-[1.5rem] text-on-surface-variant">
                <AlertCircle className="w-4 h-4 shrink-0" />
                <p className="text-label-md font-medium">No medications listed</p>
              </div>
            )}

            {/* General notes */}
            {prescription.notes && (
              <div className="section">
                <p className="flex items-center gap-1.5 text-label-md font-bold uppercase tracking-widest text-on-surface-variant mb-3">
                  <CalendarDays className="w-3 h-3" /> Doctor&apos;s Notes
                </p>
                <div className="p-5 bg-surface-container-low border border-outline-variant/20 rounded-[1.5rem]">
                  <p className="text-body-md text-on-surface-variant font-medium leading-relaxed">{prescription.notes}</p>
                </div>
              </div>
            )}
          </div>

          {/* Print button (bottom) */}
          <button
            onClick={handlePrint}
            className="w-full flex items-center justify-center gap-2 py-4 bg-surface-container-low text-on-surface font-bold text-label-lg rounded-full border border-outline-variant/30 hover:bg-surface-container-high transition-all"
          >
            <Download className="w-5 h-5" /> Download / Print
          </button>
        </div>
      </div>
    </div>
  );
}
